Repository pawtograder/platform, pull requests merged in 2025-05, with the labels that each got.

#35 #15 - Implemented filtering, searching, and sorting for discussion threads and fixed a bug
  app/course/[course_id]/discussion/DiscussionThreadList.tsx
  app/course/[course_id]/discussion/[root_id]/page.tsx
Labels: enhancement

#34 #16 - refinedev/react-table filtering moved to client-side
  app/course/[course_id]/manage/assignments/[assignment_id]/assignmentsTable.tsx
  app/course/[course_id]/manage/course/audit/page.tsx
  app/course/[course_id]/manage/course/enrollments/page.tsx
Labels: bug

#37 #17 - edit forms should populate correctly now
  app/course/[course_id]/manage/assignments/[assignment_id]/autograder/page.tsx
  app/course/[course_id]/manage/assignments/[assignment_id]/edit/page.tsx
Labels: bug

#36 #13 - fixed async race condition
  app/course/[course_id]/discussion/DiscussionThreadList.tsx
  hooks/useCourseController.tsx
  hooks/useDiscussionThreadRootController.tsx
Labels: bug

#42 #16 - Should Fix Sorting
  app/course/[course_id]/manage/assignments/[assignment_id]/assignmentsTable.tsx
  app/course/[course_id]/manage/course/audit/page.tsx
  app/course/[course_id]/manage/course/enrollments/page.tsx
Labels: frontend

#46 #45 - Fixed edit form and added toast
  app/course/[course_id]/manage/assignments/[assignment_id]/edit/page.tsx
Labels: frontend

#48 #20 - Added Migration for Rubric Check Points Update
  supabase/db-triggers-functions/User registration trigger.sql
  supabase/migrations/20250506175715_update_rubric_check_points_trigger.sql
Labels: database

#49 #21 - Instructors can now edit some student profile details
  app/course/[course_id]/manage/course/enrollments/editStudentProfileModal.tsx
  app/course/[course_id]/manage/course/enrollments/page.tsx
  supabase/migrations/20250506230720_add_instructor_profile_policy.sql
Labels: enhancement, frontend, database

#62 #26: Just the DB and Type changes
  app/course/UserMenu.tsx
  app/course/[course_id]/assignments/[assignment_id]/submissions/[submissions_id]/files/page.tsx
  app/course/[course_id]/manage/assignments/[assignment_id]/rerun-autograder/page.tsx
  app/course/[course_id]/manage/assignments/[assignment_id]/rubric/page.tsx
  public/RubricSchema.json
  supabase/functions/_shared/SupabaseTypes.d.ts
  supabase/migrations/20250512194601_add_reviews.sql
  supabase/migrations/20250512213308_add_rls_policies_for_reviews.sql
  supabase/migrations/20250512230142_add_rubric_is_private.sql
  supabase/migrations/20250512232507_refine_rls_rubric_components_visibility.sql
  supabase/migrations/20250513205131_review_assignments_new_columns.sql
  utils/supabase/SupabaseTypes.d.ts
Labels: database

#71 #69 - Fix Points Possible Form Bug
  app/course/[course_id]/manage/assignments/[assignment_id]/groups/bulkCreateGroupModal.tsx
  app/course/[course_id]/manage/assignments/new/form.tsx
  app/course/[course_id]/manage/assignments/new/page.tsx
Labels: frontend

#77 #75 - Graders can now view and create grading conflicts that involve themselves
  app/course/[course_id]/manage/course/grading-conflicts/addConflictDialog.tsx
  app/course/[course_id]/manage/course/grading-conflicts/gradingConflictsTable.tsx
  app/course/[course_id]/manage/course/grading-conflicts/page.tsx
  hooks/useClassProfiles.tsx
  supabase/migrations/20250524034121_update_grading_conflicts_rls.sql
Labels: frontend, database

#86 fix tag menu dark mode
  app/course/[course_id]/manage/course/enrollments/page.tsx
Labels: frontend

#76 #72 - Rubric Check Reference Enhancements
  app/course/[course_id]/assignments/[assignment_id]/submissions/[submissions_id]/addRubricReferenceModal.tsx
  app/course/[course_id]/assignments/[assignment_id]/submissions/[submissions_id]/files/page.tsx
  app/course/[course_id]/assignments/[assignment_id]/submissions/[submissions_id]/layout.tsx
  app/course/[course_id]/assignments/[assignment_id]/submissions/[submissions_id]/page.tsx
  app/course/[course_id]/assignments/[assignment_id]/submissions/layout.tsx
  app/course/[course_id]/grade/assignments/[assignment_id]/submissions/[submissions_id]/page.tsx
  app/course/[course_id]/manage/assignments/[assignment_id]/rubric/page.tsx
  app/course/[course_id]/manage/course/enrollments/page.tsx
  components/ui/assignment-grading-toolbar.tsx
  components/ui/code-file.tsx
  components/ui/message-input.tsx
  components/ui/rubric-sidebar.tsx
  hooks/useAssignment.tsx
  hooks/useSubmission.tsx
  supabase/migrations/20250524013334_update_submissions_after_insert_hook.sql
  supabase/migrations/20250530000000_enable_realtime_for_comments.sql
  utils/supabase/DatabaseTypes.d.ts
Labels: enhancement, frontend
