Repository pawtograder/platform, pull requests merged in 2025-08, with the labels that each got.

#166 Fix some races throughout discussion thread and profile rendering pipeline
  README.md
  app/course/[course_id]/discussion/DiscussionThreadList.tsx
  app/course/[course_id]/discussion/discussion_thread.tsx
  app/course/[course_id]/instructorDashboard.tsx
  app/course/[course_id]/manage/assignments/[assignment_id]/regrade-requests/RegradeRequestsTable.tsx
  app/course/[course_id]/office-hours/[queue_id]/request/[help_request_id]/meet/meeting.tsx
  app/course/[course_id]/studentDashboard.tsx
  hooks/useCourseController.tsx
  hooks/useGradebook.tsx
  hooks/useUserProfiles.tsx
  lib/TableController.ts
  playwright.config.ts
  tests/e2e/discussion-threads.test.tsx
  tests/e2e/enrollments.test.tsx
  tests/e2e/grading.test.tsx
  tests/e2e/office-hours.test.tsx
Labels: frontend

#165 Rubric Point Validation
  app/course/[course_id]/manage/assignments/[assignment_id]/rubric/page.tsx
  components/ui/rubric-sidebar.tsx
  tests/e2e/rubric-editor.test.tsx
Labels: frontend, testing

#171 Admin portal, SIS integration, invitation management by SIS ID
  app/actions.ts
  app/admin/classes/ClassManagementTable.tsx
  app/admin/classes/CreateClassModal.tsx
  app/admin/classes/EditClassModal.tsx
  app/admin/classes/SectionManagementModal.tsx
  app/admin/classes/page.tsx
  app/admin/import/page.tsx
  app/admin/layout.tsx
  app/admin/page.tsx
  app/admin/sis-sync/page.tsx
  app/auth/callback/route.ts
  app/course/[course_id]/dynamicCourseNav.tsx
  app/course/[course_id]/layout.tsx
  app/course/[course_id]/manage/course/enrollments/enrollmentsTable.tsx
  app/course/[course_id]/manage/course/enrollments/page.tsx
  app/course/[course_id]/manage/course/lab-sections/page.tsx
  app/course/[course_id]/manage/gradebook/importGradebookColumn.tsx
  app/course/layout.tsx
  app/course/page.tsx
  components/ui/student-lab-section.tsx
  components/ui/term-selector.tsx
  hooks/useCourseController.tsx
  hooks/useGradebook.tsx
  lib/edgeFunctions.ts
  lib/ssrUtils.ts
  package.json
  supabase/config.toml
  supabase/functions/_shared/EnrollmentUtils.ts
  supabase/functions/_shared/FunctionTypes.d.ts
  supabase/functions/_shared/GitHubWrapper.ts
  supabase/functions/_shared/HandlerUtils.ts
  supabase/functions/_shared/InvitationUtils.ts
  supabase/functions/_shared/SupabaseTypes.d.ts
  supabase/functions/assignment-delete/index.ts
  supabase/functions/assignment-group-approve-request/index.ts
  supabase/functions/autograder-create-submission/index.ts
  supabase/functions/autograder-sync-staff-team/index.ts
  supabase/functions/autograder-sync-student-team/index.ts
  supabase/functions/course-import-sis/deno.json
  supabase/functions/course-import-sis/index.ts
  supabase/functions/deno.json
  supabase/functions/deno.lock
  supabase/functions/invitation-create/deno.json
  supabase/functions/invitation-create/index.ts
  supabase/functions/submission-serve-artifact/index.ts
  supabase/functions/user-fetch-azure-profile/deno.json
  supabase/functions/user-fetch-azure-profile/index.ts
  supabase/migrations/20250330003141_remote_schema.sql
  supabase/migrations/20250813234857_office-hours-and-notifications.sql
  supabase/migrations/20250820183345_invitation_system.sql
  supabase/migrations/20250820185937_admin_portal_system.sql
  supabase/migrations/20250820193612_sis_sync_cron_job.sql
  supabase/migrations/20250821185307_fix-view-visibility.sql
  supabase/seed.sql
  tests/e2e/enrollments.test.tsx
  utils/supabase/DatabaseTypes.d.ts
  utils/supabase/SupabaseTypes.d.ts
Labels: frontend, backend, database

#183 GitHub webhook resiliency
  app/course/[course_id]/manage/workflow-runs/page.tsx
  app/course/[course_id]/manage/workflow-runs/runs/page.tsx
  components/github/link-account.tsx
  hooks/useSubmissionReview.tsx
  supabase/functions/_shared/EnrollmentUtils.ts
  supabase/functions/_shared/GitHubWrapper.ts
  supabase/functions/_shared/SupabaseTypes.d.ts
  supabase/functions/assignment-create-all-repos/index.ts
  supabase/functions/autograder-create-submission/index.ts
  supabase/functions/course-import-sis/index.ts
  supabase/functions/deno.json
  supabase/functions/deno.lock
  supabase/functions/github-repo-webhook/index.ts
  supabase/functions/gradebook-column-recalculate/expression/DependencySource.ts
  supabase/functions/gradebook-column-recalculate/index.ts
  supabase/functions/notification-queue-processor/index.ts
  supabase/functions/scripts/TriggerBulkSubmissions.ts
  supabase/migrations/20250826115031_sis-import-public-profile-name.sql
  supabase/migrations/20250826123401_github-webhook-resiliency.sql
  supabase/seed.sql
  utils/supabase/SupabaseTypes.d.ts
Labels: enhancement, frontend, backend, database

#170 Embedded Pyret REPL
  .envrc
  .gitignore
  README.md
  app/course/[course_id]/assignments/[assignment_id]/submissions/[submissions_id]/results/page.tsx
  components/github/unlink-account.tsx
  flake.lock
  flake.nix
  package-lock.json
  package.json
  scripts/AddUserToClassAsInstructor.ts
  scripts/CreateTestUsers.ts
  scripts/ExportMissingUsers.ts
  scripts/GenerateMagicLink.ts
  tests/e2e/TestingUtils.ts
  tests/e2e/pyret-repl.test.tsx
  utils/supabase/check-env-vars.ts
  utils/supabase/client.ts
  utils/utils.ts
Labels: autograding, frontend
